version: '3.1'


services:
  postgres: 
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - ./data/pgdata:/var/lib/postgresql/data:delegated
    ports:
      - '5432:5432'

  app:
    image: yiisoftware/yii2-php:8.1-apache
    environment:
      DDBB_PASSWORD: ${DATABASE_PASS}
      DDBB_USER: ${DATABASE_USER}
      DDBB_NAME: ${DATABASE_NAME}
      DDBB_HOST: ${DATABASE_HOST}
      PRODUCCION: ${PRODUCCION}
    
    volumes:
      - ./backend/composer/cache:/root/.composer/cache:delegated
      - ./backend/basic:/app:delegated
    ports:
      - '8000:80'